[project]
name = "video_gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agentkit-sdk-python==0.8.1",
    "google-adk==2.2.0",
    "veadk-python==1.0.9",
    "tos==2.8.7",
    "volcengine-python-sdk==5.0.43",
    "litellm==1.83.14",
    "json-repair==0.61.7"
]